name: face_id_plus
version: 7.6.8+18
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cached_network_image: any
  camera: any
  carousel_slider: any
  charts_flutter: ^0.12.0
  connectivity: any
  convex_bottom_bar: ^3.0.0
  cupertino_icons: any
  dart_ping: any
  dropdown_button2: any
  equatable: any
  ffi: any
  firebase_core: any
  firebase_messaging: any
  flutter_bloc: any
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.1
  flutter_local_notifications: any
  flutter_pdfview: ^1.2.2
  flutter_signature_pad: ^3.0.1
  flutter_slidable: any
  geolocator: any
  get: ^4.6.5
  get_cli: ^1.8.1
  google_maps_flutter: ^2.1.8
  http: ^0.13.4
  image: any
  image_gallery_saver: ^1.7.1
  image_picker: any
  internet_connection_checker: any
  intl: any
  intro_slider: any
  lazy_load_scrollview: any
  location: ^4.3.0
  network_info_plus: any
  path_provider: any
  permission_handler: any
  platform_device_id: any
  printing: ^5.9.2
  provider: any
  pull_to_refresh: any
  rounded_loading_button: any
  shared_preferences: any
  socket_io_client: any
  sqflite: any
  syncfusion_flutter_pdfviewer: ^20.2.39-beta
  table_calendar: any
  timer_builder: any
  uuid: ^3.0.6
  barcode_widget: any
  qrscan: ^0.3.3
  mobile_scanner: ^2.0.0
  url_launcher: ^6.1.5
  email_validator: ^2.1.17
  package_info_plus: 1.4.3+1
  flutter: 
    sdk: flutter
  flutter_datetime_picker: 
    git: https://github.com/Realank/flutter_datetime_picker.git
  dynamic_height_grid_view: ^0.0.3
  device_info_plus: ^4.1.2
  random_string: ^2.3.1
  flutter_otp_text_field: ^1.1.1
  flutter_ringtone_player: ^3.2.0
  assets_audio_player: ^3.0.5
  dio: ^4.0.6
  flex_color_picker: ^2.6.1
  signature: ^5.3.0

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter_icons: 
  image_path_android: assets/icabp.png
  image_path_ios: assets/ic_abp.jpg
  android: true
  ios: true

flutter: 
  assets: 
    - assets/images/abp.png
    - assets/alarm.mp3
    - assets/images/roster_ic.png
    - assets/images/roster_add_ic.png
    - assets/images/list_cuti_ic.png
    - assets/images/dev.png
    - assets/images/ic_abp.png
    - assets/ic_abp.jpg
    - assets/abpicon.png
    - assets/abpicon_black.png
    - assets/ic_abp.ico
    - assets/images/abp_60x60.png
    - assets/images/abp_maps.png
    - assets/images/abp_ic.png
    - assets/images/sarana.png
    - assets/images/sarana_add.png
    - assets/images/ob.png
    - assets/images/crushing.png
    - assets/images/hauling.png
    - assets/images/product_stock.png
    - assets/images/stock.png
    - assets/images/total_rkb.png
    - assets/images/appr_rkb.png
    - assets/images/cancel_rkb.png
    - assets/images/close_rkb.png
    - assets/images/waiting_rkb.png
    - assets/images/monitoring.png
    - assets/images/barging.png
    - assets/images/barging_pln.png
    - assets/images/tugboat.png
    - assets/images/p2h.png
    - assets/images/unit.png
    - assets/icon.png
    - assets/ic_abp.png
    - assets/icabp.png
    - assets/load.gif
    - assets/images/new_user.png
    - assets/images/login_ic.png
    - assets/images/car_ic.png
    - assets/images/mine_permit.psd
    - assets/images/SIMPER_ABP.psd
  uses-material-design: true

